create database if not exists Sis-Pedido;

create Table if not exists ID_PRODUCTO(
ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR (50) NOT NULL,
DESCRIPCION VARCHAR(1000) NOT NULL,
PRECIO DECIMAL (10,2) NOT NULL,
CANTIDAD INT NOT NULL
)